### ISSUE TITLE
Won't work with Sketch 53

### ISSUE THREAD

**Issue by ventrebleu** [oodesign/icon-tools#3]
Hello,

Apparently "Prepare icons for export" doesn't work anymore with Sketch 53.

**Comment by oodesign** [comment]
Hi @ventrebleu !

We just released version 1.0.9, that enables support for Sketch 53. May you check it out and let us know if it worked for you?

Thanks!

**Comment by ventrebleu** [comment]
Thanks for the quick update!
I will let you know if I still see a problem.

Have a good one!

**Comment by oodesign** [comment]
Thanks to you for letting us know! :)
